name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy-aws:
    name: Deploy to AWS ECS
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Force ECS redeploy
        run: |
          aws ecs update-service \
            --cluster devops-assignment-cluster \
            --service backend-service \
            --force-new-deployment

          aws ecs update-service \
            --cluster devops-assignment-cluster \
            --service frontend-service \
            --force-new-deployment


  deploy-gcp:
    name: Build & Deploy to GCP Cloud Run
    runs-on: ubuntu-latest
    needs: deploy-aws

    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker -q

      # -------- BACKEND --------
      - name: Build & Push Backend Image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/backend:latest ./backend
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/backend:latest

      - name: Deploy Backend to Cloud Run
        run: |
          gcloud run deploy backend-service \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/backend:latest \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated

      # -------- FRONTEND --------
      - name: Build & Push Frontend Image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/frontend:latest ./frontend
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/frontend:latest

      - name: Deploy Frontend to Cloud Run
        run: |
          gcloud run deploy frontend-service \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/frontend:latest \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated

